### ISSUE TITLE
Run tests along `yarn tsc` and `yarn autotsc` commands

### ISSUE THREAD

**Issue by tmjoseantonio** [tmjoseantonio/typescript-boilerplate#1]
`ts-test` is installed but is not running tests when the yarn tsc / autotsc command is executed.

It would be nice to run tests while the TypeScript compiler is running.

**Comment by ChrisMcNulty91** [comment]
@tmjoseantonio  I can take a look at this

**Comment by ChrisMcNulty91** [comment]
@tmjoseantonio the tsc command doesn't execute. This is what I get 
`error TS6053: File 'app/**/*.ts' not found.
error Command failed with exit code 2.`

**Comment by tmjoseantonio** [comment]
@ChrisMcNulty91 run `yarn tsc` or `yarn autotsc`
