### ISSUE TITLE
Add TypeScript linter

### ISSUE THREAD

**Issue by tmjoseantonio** [tmjoseantonio/typescript-boilerplate#2]
The current webpack task is compiling TypeScript and SCSS, however is not running any kind of lint, which would be really useful for anyone who wants to use this boilerplate.

It would be awesome to implement airbnb linter
https://www.npmjs.com/package/tslint-config-airbnb

**Comment by rixlabs** [comment]
I can do it!

**Comment by tmjoseantonio** [comment]
Cool, thank you @rixlabs !

**Comment by tmjoseantonio** [comment]
To contribute you can fork the project, commit your changes and send the pull request.

**Comment by rixlabs** [comment]
Hey you'r project actually doesn't build any typescript. I'll fix your config also for that.
If you want to try just add this:
```
const a:string = 'a';
```
to your index.ts

**Comment by tmjoseantonio** [comment]
Amazing @rixlabs I appreciate your help
